apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "api.fullname" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.RegSec }}
      containers:
        - name: backend
          image: {{ .Values.image.repository }}
          #command:
          #- "java"
          #- "-javaagent:/apm-agent.jar"
          #- "-Delastic.apm.active=true"
          #- "-Delastic.apm.server_urls=http://apm-server-apm-server:8200"
          #- "-Delastic.apm.service_name=spring-boot-app"
          #- "-jar"
          #- "springboot2-jpa-crud-example.jar"
          ports:
            - containerPort: 8090
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 400m
              memory: 400Mi
            limits:
              memory: "500Mi"
              cpu: "500m"  
          env:
          - name: SPRING_DATASOURCE_URL
            #valueFrom:
              #secretKeyRef:
                #name: {{ include "api.fullname" . }}-secret
                #key: database-uri
            valueFrom:
              configMapKeyRef:
                name: configdb
                key: database-uri
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "api.fullname" . }}-secret
                key: database-password
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "api.fullname" . }}-secret
                key: database-user
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: {{ include "api.fullname" . }}
  labels: 
    app: {{ include "api.fullname" . }}
spec:      
  type: {{ .Values.service.type }}                   
  selector:
    app: {{ include "api.fullname" . }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8090
