apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels: 
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.RegSec }}
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8090
          imagePullPolicy: IfNotPresent
          env:
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "api.fullname" . }}-secret
                key: database-password
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "api.fullname" . }}-secret
                key: database-user
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "api.fullname" . }}-secret
                key: database-uri

---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: {{ include "api.fullname" . }}
  labels: 
    {{- include "api.labels" . | nindent 4 }}
spec:      
  type: ClusterIP                   
  selector:
    {{- include "api.selectorLabels" . | nindent 6 }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8090
