apiVersion: v1
kind: Service
metadata:
  name: postgres-db-svc
spec:
  ports:
  - port: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-db-svc
subsets:
  - addresses:
      - ip: {{ .Values.db.dbip }}
    ports:
      - port: 5432
