apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secret 
type: Opaque
data:
  database-uri: {{ .Values.uri | b64enc }}
  database-user: {{ .Values.username | b64enc }}
  database-password: {{ .Values.password | b64enc }}
