apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secret 
data:
  database-uri: {{ with .Values.secret.database_uri -}}
  {{- list "jdbc:postgresql://" .dbip ":" .dbport "/" .dbname .dbconn | join ""  | b64enc |  quote }}
# {{- ( printf "%s%s:%s@%s-%s%s" "mongodb://" .username .password $.Release.Name "database" ":27017/guestbook?authSource=admin" ) | b64enc | quote }}
  {{- end }}
  database-user: {{ .Values.secret.database_uri.username | join "" | b64enc |  quote }}
  database-password: {{ .Values.secret.database_uri.password | join "" | b64enc |  quote }}
