apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "crud.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "crud.fullname" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.RegSec }}
      containers:
        - name: frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 350m
              memory: 350Mi
            limits:
              memory: "400Mi"
              cpu: "400m"
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: {{ include "crud.fullname" . }}
  labels: 
    app: {{ include "crud.fullname" . }}
spec:
  type: {{ .Values.service.type }}               
  selector:
    app: {{ include "crud.fullname" . }}
  ports:                      
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
