apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      containers:
      - name: {{ include "backend.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
          limits:
            memory: "500Mi"
            cpu: "500m"   
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: database-password
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: database-user
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: database-uri
      imagePullSecrets:
      - name: regcred         
