apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud.fullname" . }}
  labels: 
    {{- include "crud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crud.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.RegSec }}
      containers:
        - name: frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: {{ include "crud.fullname" . }}
  labels: 
    {{- include "crud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}               
  selector:
    {{- include "crud.selectorLabels" . | nindent 6 }}
  ports:                      
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
