apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
    cert-manager.io/cluster-issuer: {{ .Values.issuer | quote }}
    "letsencrypt-prod"
spec:
  tls:
{{- range .Values.ingress.hosts }}
  - hosts: {{ .host.domain }}
    secretName: {{ .Values.issuer }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ .host.domain }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ include "crud.fullname" $ }}
          servicePort: {{ .host.port }}
{{- end }}
