apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
      - {{ .host.domain }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host.domain }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ include "crud.fullname" $ }}
          servicePort: {{ .host.port }}
  {{- end }}
