apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
     kubernetes.io/ingress.class: alb
     alb.ingress.kubernetes.io/scheme: internet-facing
     alb.ingress.kubernetes.io/target-type: instance
spec:
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host.domain }}
    {{- end }}
    secretName: secret-tls
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host.domain }}
    http:
      paths:
      {{- if .host.chart }}
      - path: /restapi/(.+)
        backend:
          serviceName: {{ $.Release.Name }}-{{ .host.chart }}
          servicePort: {{ .host.port }}
      {{ else }}
      - path: /(.*)
        backend:
          serviceName: {{ include "crud.fullname" $ }}
          servicePort: {{ .host.port }}
      {{- end }}
  {{- end }}
