apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.secret }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "crud.fullname" $ }}
          servicePort: {{ .Values.service.port }}
      - path: /(.+)
        backend:
          serviceName: {{ include "api.fullname" $ }}
          servicePort: {{ .Values.apiport }}
