apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host.domain }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ $.Release.Name}}-{{ .host.chart }}
          servicePort: {{ .host.port }}
  {{- end }}
