#AWS Access Key
AWS_ACCESS_KEY_ID = "AKIAIVL6CPRLCBLIQMAA"
#AWS Secret Key
AWS_SECRET_ACCESS_KEY = "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"
#EC2 SSH Key Name
AWS_SSH_KEY_NAME = "keypair_aws"
#AWS Region
AWS_DEFAULT_REGION = "eu-west-2"
