pipeline {
	agent{
		node{
			label 'master'
		}
	}
	triggers {
		pollSCM('* * * * *') //runs this pipeline on every commit
		//cron('30 23 * * *') //run at 23:30:00 
    	}

	stages {
		stage('Git Checkout'){
			steps{
				cleanWs()
				checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'app']]]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'gitCred', url: 'https://github.com/erahaouisamia/repo_idemia/']]])
			}
        	}
		stage('Compile && build jar && docker image'){
			steps {
				dir("${env.WORKSPACE}/app/crud-api"){
					withDockerContainer(image: 'maven:3.6.3-openjdk-8')
					{
						sh label: '', script: 'mvn clean compile'
						sh 'mvn clean package'
					}
					sh 'docker build -t backend:v1 .'
				}
			}
		}
		stage('Frontend && docker image'){
			steps {
				dir("${env.WORKSPACE}/app/crud-frontend")
				{
					withDockerContainer(image: 'node:latest'){
						//sh 'npm install'
						sh 'npm run build -- --prod' 
					}
					sh 'docker build -t frontend:v1 .'
				}
			}
		}
        	stage ('docker image push to Nexus') {
		    steps {
			withCredentials(usernamePassword(credentialsId: 'nexus-registry', usernameVariable: 'nexus_user', passwordVariable: 'nexus_password')){
				sh 'docker login -u \$nexus_user -p \$nexus_password http://3.9.82.208:8083'
				sh 'docker push backend:v1'
				sh 'docker push frontend:v1'
			}
		    }
        	}
		stage ('helm push to Nexus') {
			steps {
				dir("${env.WORKSPACE}/app"){
					withCredentials([usernamePassword(credentialsId: 'nexus-registry', usernameVariable: 'nexus_user', passwordVariable: 'nexus_password')]){
						withDockerContainer(args: '--entrypoint=', image: 'alpine/helm'){
							sh 'helm plugin install --version master https://github.com/sonatype-nexus-community/helm-nexus-push.git'
							sh 'helm repo add helmRepo http://http://3.9.82.208:8081/repository/helmRepo/ --username \$nexus_user --password \$nexus_password'
							sh 'helm nexus-push helmRepo app/Helm-chart --username \$nexus_user --password \$nexus_password'
						}
		    			}
        			}
			}
		}
    	}
	post {
	    success {
	      deleteDir()
	    }
  	}
}
