pipeline {
	agent{
	    node{
	      label 'slave'
	    }
  }
  //triggers {
    //pollSCM 'H/2 * * * *'
  //}

	stages {
		stage("Git Checkout"){
      steps{
        cleanWs()
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'Database']]]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'gitCred', url: 'https://github.com/erahaouisamia/repo_idemia/']]])

      }
    }
    stage('Build img') {
      steps {
         dir("${env.WORKSPACE}"){
            withDockerContainer(args: '--entrypoint=',image: 'hashicorp/packer') {
              sh label: '', script: 'packer build Database/packer_image.json'
            }
  		  }
      }
      post {
        success {
          sh 'docker image rm -f hashicorp/packer'
        }
    }
  }
}
  post {
    success {
      deleteDir()
    }
  }
}
