apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host.domain }}
    {{- end }}
    secretName: {{ .Values.secret }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host.domain }}
    http:
      paths:
      {{- if .host.chart }}
      - path: /restapi/(.+)
        backend:
          serviceName: {{ $.Release.Name }}-{{ .host.chart }}
          servicePort: {{ .host.port }}
      {{ else }}
      - path: /(.*)
        backend:
          serviceName: {{ include "crud.fullname" $ }}
          servicePort: {{ .host.port }}
      {{- end }}
  {{- end }}