apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secret 
type: Opaque
data:
    #{{ with .Values.db -}}
    #{{- list "jdbc:postgresql://" .dbip ":" .dbport "/" .dbname .dbconn | join ""  | b64enc |  quote }}
  #{{- end }}
  database-user: {{ .Values.db.username | join "" | b64enc |  quote }}
  database-password: {{ .Values.db.password | join "" | b64enc |  quote }}