---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: crud
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:v*
spec:
  releaseName: crud-app
  chart:
    git: ssh://git@github.com/erahaouisamia/repo_idemia.git
    path: app/helm-chart
    ref: master
