apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: {{ include "frontend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend.fullname" . }}
    spec:
      containers:
      - name: {{ include "frontend.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  
        imagePullPolicy: IfNotPresent    
        resources:
            requests:
              cpu: 350m
              memory: 350Mi
            limits:
              memory: "400Mi"
              cpu: "400m" 
        ports:
        - name: "http"
          containerPort: 80
        env:
        - name: BACKEND_URI
          valueFrom:
            configMapKeyRef:
              name: {{ include "frontend.fullname" . }}-config
              key: backend-uri
      imagePullSecrets:
      - name: regcred         

