apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app: {{ include "frontend.fullname" . }}
spec:
  ports:
  - port:  {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ include "frontend.fullname" . }}
  type: {{ .Values.service.type }}