pipeline {
  agent{
    node{
      label 'slave'
    }
  }
  stages {
    stage("Git Checkout"){
      steps{
        cleanWs()
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'kubespray']]]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'gitCred', url: 'https://github.com/erahaouisamia/repo_idemia/']]])
      }
    }
    stage('terraform'){
      steps{
        dir("${env.WORKSPACE}/kubespray"){
          withDockerContainer(args: '--entrypoint=',image: 'hashicorp/terraform') {
              dir("contrib/terraform/aws"){
                sh 'terraform init'
                sh 'terraform plan -out kubespray --var-file="credentials.tfvars"'
                input(message: 'approve the plan to proceed and apply', ok: 'Yes !')
                sh 'terraform apply "kubespray"'
              }
          }
        //}
          //dir("${env.WORKSPACE}/kubespray"){
              withCredentials([usernamePassword(credentialsId: 'gitCred', usernameVariable: 'Github_user', passwordVariable: 'Github_pass')]){
                sh 'git config --global user.email "samiaerahaoui.aws@gmail.com"'
                sh 'git config --global user.name $Github_user'
                sh 'git remote rm origin'
                sh 'git remote add origin https://${Github_user}:${Github_pass}@github.com/erahaouisamia/repo_idemia.git > /dev/null 2>&1'
                sh 'git add inventory/hosts contrib/terraform/aws/kubespray'
                sh 'git commit -m "Added file with automated Jenikins job Terraform"'
                sh 'git push origin HEAD:master'
              }
            }
          }
          post {
            success {
              sh 'docker image rm -f hashicorp/terraform'
            }
          }
        }
    stage('Create k8s cluster') {
      steps{
        withCredentials([file(credentialsId: 'private_key', variable: 'private_key'),usernamePassword(credentialsId: 'nexus-registry', usernameVariable: 'nexus_user', passwordVariable: 'nexus_password')])
        {
          //sh 'cd /home'
          //sh 'mkdir /home/jenkins/.ssh && chmod 700 /home/jenkins/.ssh'
          dir("${env.WORKSPACE}/kubespray"){
            sh 'cp \$private_key /home/ubuntu/.ssh/kubespray.pem'
            sh 'chmod 600 /home/ubuntu/.ssh/kubespray.pem'
            sh 'eval $(ssh-agent) && ssh-add -D && ssh-add /home/ubuntu/.ssh/kubespray.pem'
            sh 'sudo pip3 install -r requirements.txt'
            sh 'ansible-playbook -i inventory/hosts cluster.yml -e ansible_user=ubuntu -e ansible_python_interpreter="/usr/bin/python3" --become-user=root --flush-cache -b'
            //sh 'ansible-playbook deploy_app_k8s.yml -e ansible_python_interpreter="/usr/bin/python3" -e nexus_username=$nexus_user -e nexus_password=$nexus_password'
          }
        }
      }
    }
    stage("git push"){
      steps{
        dir("${env.WORKSPACE}/kubespray"){
          withCredentials([usernamePassword(credentialsId: 'gitCred', usernameVariable: 'Github_user', passwordVariable: 'Github_pass')]){
            sh 'git config --global user.email "samiaerahaoui.aws@gmail.com"'
            sh 'git config --global user.name $Github_user'
            sh 'git remote rm origin'
            sh 'git remote add origin https://${Github_user}:${Github_token}@github.com/erahaouisamia/repo_idemia.git > /dev/null 2>&1'
            sh 'git add ssh-bastion.conf'
            sh 'git commit -m "Added file with automated Jenikins job Terraform"'
            sh 'git push origin HEAD:master'
          }
        }
      }
    }
  }
  post {
    success {
      deleteDir()
    }
  }
}
