pipeline {
	agent any

	stages {
		stage("Git Checkout"){
      			steps{
            			checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'kubespray']]]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'gitCred', url: 'https://github.com/erahaouisamia/repo_idemia/']]])
      			}
    		}
		stage('terraform'){
		      	agent{
				docker{
			      		image 'hashicorp/terraform'
				}
		      	}
			steps{
				dir("kubespray/contrib/terraform/aws/terraform"){
						//sh label: '', script: 'cd kubespray/contrib/terraform/aws/terraform'
					sh label: '', script: 'docker run hashicorp/terraform init'
					sh label: '', script: 'docker run hashicorp/terraform plan kubespray -var-file=credentials.tfvars'
					sh label: '', script: 'terraform apply "kubespray"'
				}
			}
		}
		stage('Ansible') {
			agent{
				docker{
					image 'geektechstuff/ansible_container'
				 }
			 }
			 steps {
				dir("kubespray"){
					sh label: '', script: 'docker run geektechstuff/ansible_container -i ./inventory/hosts ./cluster.yml -e ansible_user=core -b --become-user=root --flush-cache'
				}
		      	    }
		}
  }
}
