# Default values for crud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  RegSec: prvrg

api:
  db:
    dbip:
    dbport: 5432
    username: postgres
    password: postgres
    dbname: db_example
    dbconn: ?ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory

image: repos.nexus.com:48083/frontend:1

replicaCount: 1

service:
  type: NodePort
  port: 80

secret: letsencrypt-prod

ingress:
  annotations:
    #kubernetes.io/ingress.class: alb
    #alb.ingress.kubernetes.io/target-type: instance
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

domain: crudemployee.com
apiport: 8090
