# Default values for crud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

RegSec: prvrg

image:
  repository: 3.10.94.103:8083/frontend
  tag: "v1"
replicaCount: 1
service:
  type: NodePort
  port: 80

ingress:
  hosts:
    - host:
        domain: crudemployee.com
        chart: frontend
        port: 80
