# Default values for crud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  RegSec: prvrg

api:
  db:
    dbip: 192.168.1.15
    dbport: 5432
    username: postgres
    password: postgres
    dbname: db_example
    dbconn: ?ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory

image:
  repository: repos.nexus.com:48083/frontend
  #tag: 1

replicaCount: 1

service:
  type: NodePort
  port: 80

ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
    #cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host:
        domain: crudemployee.com
        port: 80
    - host:
        domain: crudemployee.com
        chart: api
        port: 8090
