# Default values for crud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  RegSec: prvrg

api:
  dbip:
  username: postgres
  password: postgres
  dbname: employeedb
  uri: jdbc:postgresql://{{ .Values.api.dbip }}:5432/{{ .Values.api.dbname }}/?ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory

image: repos.nexus.com:48083/frontend:3

replicaCount: 1

service:
  type: LoadBalancer
  port: 80

secret: letsencrypt-prod

ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host:
        domain: crudemployee.com
        port: 80
    - host:
        domain: crudemployee.com
        port: 8090
