# Default values for crud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  RegSec: prvrg

api:
  db:
    dbip: 10.250.200.81
    dbport: 5432
    username: postgres
    password: postgres
    dbname: db_example
    dbconn: ?ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory

ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/certificate-arn:  arn:aws:acm:eu-west-2:305249848038:certificate/f75f2f6c-7a9f-4681-b6b0-3873417aaa47
  hosts:
    - host:
        domain: frontend.employees-app.tk
        chart: frontend
        port: 80
    - host:
        domain: employees-app.tk
        chart: api
        port: 8090
