# Default values for crud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

RegSec: prvrg
#ApiImg: 192.168.1.11:8083/springboot2-jpa-crud-example:latest
#feImg: 192.168.1.11:8083/angular_client:latest
#jdbc:mysql://crudapp-mysql:3306/db_example?allowPublicKeyRetrieval=TRUE&useSSL=false&serverTimezone=UTC

image:
  repository: 52.254.19.67:5000/frontend
  tag: "latest"
replicaCount: 1
service:
  #type: NodePort
  port: 80
  
backend:
  secret:
    database_uri:
      dbip:
ingress:
  hosts:
    - host:
        domain: crudemployee.com
        chart: frontend
        port: 80