# Default values for crud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  RegSec: prvrg
image:
  repository: repos.nexus.com:48083/frontend
  tag: "v1"
replicaCount: 1
service:
  type: LoadBalancer
  port: 80

ingress:
  hosts:
    - host:
        domain: crudemployee.com
        port: 80
