apiVersion: v2
name: employee-crud
appVersion: "1.0"
description: A Helm chart for Employees 1.0 
version: 0.1.0
type: application
dependencies:
  #- name: backend
  #  version: ~1.2.2
  #  repository: http://localhost:8080
  #- name: frontend
  #  version: ^1.2.0
  #  repository: http://localhost:8080
  #- name: database
  #  version: ~1.2.2
  #  repository: http://localhost:8080

