---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Add ubuntu user to docker group
    user:
      name: ubuntu
      group: docker

  - name: Create a container from the terraform docker image
    docker_container:
      name: "terraform"
      image: "hashicorp/terraform"
      restart_policy: on-failure

  - name: Create a container from the packer docker image
    docker_container:
      name: "packer"
      image: "hashicorp/packer"
      restart_policy: on-failure

  - name: Create a container from the packer docker image
    docker_container:
      name: "git"
      image: "bitnami/git"
      restart_policy: on-failure

  handlers:
      - name: docker status
        service: name=docker state=started